--liquibase formatted sql

--changeset stepninkv:data context:!prod
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-15', 799.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-15-PRO', 999.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-15-PRO-MAX', 1199.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-16', 899.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-16-PRO', 1099.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-16-PRO-MAX', 1299.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-17', 999.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-17-PRO', 1199.00, 1);
INSERT INTO T_ORDER (ID, ORDER_NUMBER, SKU_CODE, PRICE, QUANTITY) VALUES (ORDER_SEQ.NEXTVAL, SYS_GUID(), 'IPHONE-17-PRO-MAX', 1399.00, 1);

