--liquibase formatted sql

--changeset stepninkv:1
CREATE TABLE T_ORDER
(
  ID           NUMBER(19),
  ORDER_NUMBER VARCHAR2(50),
  SKU_CODE     VARCHAR2(100),
  PRICE        NUMBER(19, 2),
  QUANTITY     NUMBER(10),
  CONSTRAINT T_ORDER_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE ORDER_SEQ START WITH 1 INCREMENT BY 1;
