--liquibase formatted sql

--changeset stepninkv:1
CREATE TABLE INVENTORY
(
  ID       NUMBER(19),
  SKU_CODE VARCHAR2(255),
  QUANTITY NUMBER(10),
  CONSTRAINT INVENTORY_PK PRIMARY KEY (ID),
  CONSTRAINT INVENTORY_UK UNIQUE (SKU_CODE)
);

CREATE SEQUENCE INVENTORY_SEQ START WITH 1 INCREMENT BY 1;

COMMENT ON COLUMN INVENTORY.ID IS 'Уникальный идентификатор товара';
COMMENT ON COLUMN INVENTORY.SKU_CODE IS 'Уникальный код товара';
COMMENT ON COLUMN INVENTORY.QUANTITY IS 'Количество на складе';
