--liquibase formatted sql

--changeset stepninkv:data context:!prod
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-15', 0);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-15-PRO', 10);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-15-PRO-MAX', 20);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-16', 0);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-16-PRO', 20);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-16-PRO-MAX', 10);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-17', 5);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-17-PRO', 20);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'IPHONE-17-PRO-MAX', 1);
