--liquibase formatted sql

--changeset stepninkv:data context:!prod
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'APPLE-IP14-23', 50);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'APPLE-IP14-PRO', 30);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'APPLE-IP13-22', 70);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'APPLE-IPSE-22', 100);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'SAMSUNG-S23-23', 60);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'GOOGLE-PXL7-22', 40);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'XIAOMI-13-23', 50);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'ONEPLUS-11-23', 45);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'APPLE-MBA-23', 25);
INSERT INTO INVENTORY (ID, SKU_CODE, QUANTITY) VALUES (INVENTORY_SEQ.NEXTVAL, 'APPLE-IPAD-PRO', 35);
