CONNECT SYSTEM/ROOT@FREEPDB1;

CREATE USER WS_PRODUCT IDENTIFIED BY WS_PRODUCT DEFAULT TABLESPACE USERS PROFILE DEFAULT QUOTA UNLIMITED ON USERS;

GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE, CREATE VIEW TO WS_PRODUCT;

COMMIT;
