CONNECT SYSTEM/ROOT@FREEPDB1;

CREATE USER WS_PRODUCT IDENTIFIED BY WS_PRODUCT DEFAULT TABLESPACE USERS PROFILE DEFAULT QUOTA UNLIMITED ON USERS;
CREATE USER WS_ORDER IDENTIFIED BY WS_ORDER DEFAULT TABLESPACE USERS PROFILE DEFAULT QUOTA UNLIMITED ON USERS;
CREATE USER WS_INVENTORY IDENTIFIED BY WS_INVENTORY DEFAULT TABLESPACE USERS PROFILE DEFAULT QUOTA UNLIMITED ON USERS;

GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE, CREATE VIEW TO WS_PRODUCT;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE, CREATE VIEW TO WS_ORDER;
GRANT CONNECT, CREATE SESSION, CREATE TABLE, CREATE SEQUENCE, CREATE TRIGGER, CREATE PROCEDURE, CREATE TYPE, CREATE VIEW TO WS_INVENTORY;

COMMIT;
