--liquibase formatted sql

--changeset stepninkv:data context:!prod
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 15', 799.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 15 Pro', 999.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 15 Pro Max', 1199.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 16', 899.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 16 Pro', 1099.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 16 Pro Max', 1299.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 17', 999.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 17 Pro', 1199.00);
INSERT INTO PRODUCT (ID, NAME, PRICE) VALUES (PRODUCT_SEQ.NEXTVAL, 'iPhone 17 Pro Max', 1399.00);
